Chapter 8
Josesosa07/training_odoo16 pull request #1
Opened 2023-02-21 19:51 UTC by Josesosa07

2023-02-21 21:04 UTC, EmilioSerna requested changes
Hi @Josesosa07 

Could you please improve these commit messages with these conventions?

The flow to edit these messages should be with rebase, after rebase you should force push to this branch, any question you can ask me over private

https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message
https://www.odoo.com/documentation/16.0/contributing/development/git_guidelines.html#tag-and-module-name

2023-02-21 21:04 UTC, EmilioSerna commented on estate/__manifest__.py
>          # 'phone_validation',
```suggestion
```
Please remove commented code

2023-02-21 21:04 UTC, EmilioSerna commented on estate/models/estate_property.py
> +    user_id = fields.Many2one('res.users', string='Salesman', default=lambda self: self.env.user)
```suggestion
    buyer_id = fields.Many2one("res.partner", string="Buyer", readonly=True, copy=False)
    user_id = fields.Many2one("res.users", string="Salesman", default=lambda self: self.env.user)
```
Please use only quotation marks (") instead of (')

2023-02-21 21:04 UTC, EmilioSerna commented on estate/security/ir.model.access.csv
> +access_estate_property_tag,access_estate_property_tag,model_estate_property_tag,base.group_user,1,1,1,1
```suggestion
estate.access_estate_property,estate.access_estate_property,model_estate_property,base.group_user,1,1,1,1
estate.access_estate_property_type,estate.access_estate_property_type,model_estate_property_type,base.group_user,1,1,1,1
estate.access_estate_property_tag,estate.access_estate_property_tag,model_estate_property_tag,base.group_user,1,1,1,1
```
It's better to add as a prefix the name of the module

2023-02-21 21:04 UTC, EmilioSerna commented on estate/views/estate_menus.xml
> +            <menuitem id="estate_property_tag_menu_action" action="estate_property_tag_action"/>
```suggestion
            <menuitem id="estate_property_type_menu" action="estate_property_type_action"/>
            <menuitem id="estate_property_tag_menu" action="estate_property_tag_action"/>
```
[XML IDs naming convention](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#security-view-and-action)

2023-02-21 21:04 UTC, EmilioSerna commented on estate/views/estate_property_type_views.xml
> +               <field name="name" string="Name" />
I think `string="Name"` it's not necessary, can you please check it functionally?

2023-02-21 21:04 UTC, EmilioSerna commented on estate/views/estate_property_views.xml
> +                <!-- <filter string="State" name="state" domain="['|',('state', '=', 'new'),('state', '=', 'offer_received')]"/> -->
```suggestion
```
Please remove commented code

2023-02-24 00:04 UTC, Josesosa07 commented
Hola se supone ya están los cambios solicitados, o eso espero jeje

2023-02-24 15:21 UTC, EmilioSerna requested changes
These are the last comments I see, please rebase and edit the commit messages with the convention tags and messages like: `[IMP] estate: ...`

2023-02-24 15:24 UTC, EmilioSerna requested changes
These are the last comments I see, please rebase and edit the commit messages with the convention tags and messages like: `[IMP] estate: ...`

2023-02-24 15:24 UTC, EmilioSerna commented on estate/models/estate_property.py
>  local_timezone = pytz.timezone("America/Monterrey")
I don't see it being used 👀
Correct me if i'm wrong

2023-02-24 15:24 UTC, EmilioSerna commented on estate/views/estate_property_offer_views.xml
> +                        <field name="state"/>
Isn't `property_id` also required by the model?

2023-02-24 15:24 UTC, EmilioSerna commented on estate/views/estate_property_type_views.xml
> +            <tree string="Property Types">
This attribute `string` is deprecated in tree views, can you please remove it?

2023-02-24 15:24 UTC, EmilioSerna commented on estate/models/estate_property.py
>      # name = fields.Char('Estate Property Name', required=True, translate=True)
```suggestion
```
Please remove commented code

2023-02-24 15:26 UTC, EmilioSerna requested changes

2023-02-24 15:26 UTC, EmilioSerna commented on estate/models/estate_property_offer.py
> +    property_id = fields.Many2one('estate.property', string='Property', required=True)
```suggestion
    partner_id = fields.Many2one("res.partner", string="Partner", required=True)
    property_id = fields.Many2one("estate.property", string="Property", required=True)
```

2023-02-24 19:35 UTC, closed without merging